import "@styles/font.css"; // Import font styles
import "@styles/globals.css"; // Import global styles

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale }, // locale params passed to the layout
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale || "en"}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
